# ruff: noqa: F401

from vigilai.tasks.aime_2025 import aime_2025
from vigilai.tasks.arc_challenge import arc_challenge
from vigilai.tasks.bbq import bbq
from vigilai.tasks.bbq_brazil import bbq_brazil
from vigilai.tasks.bigbench_calibration import bigbench_calibration
from vigilai.tasks.bold import bold
from vigilai.tasks.boolq_contrast import boolq_contrast
from vigilai.tasks.cab import cab
from vigilai.tasks.decoding_trust import decoding_trust
from vigilai.tasks.fairllm import fairllm
from vigilai.tasks.forecast_consistency import forecast_consistency
from vigilai.tasks.gpqa_diamond import gpqa_diamond
from vigilai.tasks.hle import hle
from vigilai.tasks.human_deception import human_deception
from vigilai.tasks.human_deception_brazil import human_deception_brazil
from vigilai.tasks.ifbench import ifbench
from vigilai.tasks.imdb_contrast import imdb_contrast
from vigilai.tasks.include import include
from vigilai.tasks.instruction_goal_hijacking import instruction_goal_hijacking
from vigilai.tasks.livebench_coding import livebench_coding
from vigilai.tasks.llm_rules import llm_rules
from vigilai.tasks.mask import mask
from vigilai.tasks.mmlu_pro import mmlu_pro
from vigilai.tasks.mmlu_pro_robustness import mmlu_pro_robustness
from vigilai.tasks.mmmu_pro import mmmu_pro
from vigilai.tasks.realtoxicityprompts import realtoxicityprompts
from vigilai.tasks.self_check_consistency import self_check_consistency
from vigilai.tasks.simpleqa_verified import simpleqa_verified
from vigilai.tasks.strong_reject import strong_reject
from vigilai.tasks.swe_bench_verified import swe_bench_verified
from vigilai.tasks.triviaqa_calibration import triviaqa_calibration
from vigilai.tasks.truthfulqa import truthfulqa
